### ISSUE TITLE
Invalid path to certificate in application.yml?

### ISSUE THREAD

**Issue by ryanmccormick** [stormpath/stormpath-spring-juiser-origin-example#1]
This issue is a potential issue and more of a question. The application.yml file references the certificate at the path juiser.user.header.jwt.key.resource: classpath:rsatest.pub.pem which I have not been able to get to work. 

After digging around in the juiser library, I found a file under the juiser-spring-boot-starter project called ForwardedHeaderConfig. The ConfigurationProperties annotation shows a path of "juiser.header" as opposed to "juiser.user.header". 

When changing the property to "juiser.header" it seemed like everything worked. Is this accurate?

**Comment by andersonkyle** [comment]
@ryanmccormick You're right.  This was changed in [df991ad](https://github.com/juiser/juiser/commit/df991adaed56696de26d5ddac238771ed041258a)

PR #2 updates this example project.

**Comment by mraible** [comment]
Closing since the PR has been merged.
